### ISSUE TITLE
Any plan on releasing Swift Package Support?

### ISSUE THREAD

**Issue by davidhakki** [customerly/Customerly-iOS-SDK#10]
Would make integration easier and far superior vs cocoa pods.

**Comment by harrycamelback** [comment]
Hi there. 
In the future we will certainly integrate Swift Package Manager, but at the moment it does not support some features that are necessary to make the SDK work, for example it does not allow you to add external resources. These limits will disappear in the next versions of the package manager, and it will then be possible to use it for our SDK.

**Comment by davidhakki** [comment]
Sorry to re-open this, but Xcode 12.2 has released with an update to SPM, I am not sure if it is now possible to revisit this issue yet? If it is still not possible, what would be the steps to manually integrate since we have moved our projects away from cocoa pods.
