### ISSUE TITLE
CROSS BUTTON DISAPPEAR

### ISSUE THREAD

**Issue by Faizanali-matechco** [customerly/Customerly-iOS-SDK#2]
I am facing an issue when the conversation list present some time the cross button on navigation bar disappear and then it remain hidden until the app must be kill.

**Comment by pmusolino** [comment]
Do you have a screenshot, just to make sure I understood the problem? 
Can you give me also more information like simulator, iOS version, etc..?
Thanks

**Comment by benlmyers** [comment]
If you're referring to `closeButton` in `CyViewController.swift`, I don't see anything that modifies the properties of `closeButton` such that it gets hidden. Have you ensured the status bar's z-position is not changing to obstruct the button's view?

-Ben

**Comment by harrycamelback** [comment]
@Faizanali-matechco please, let us know if you solved the problem. For the moment I close the issue.
