### ISSUE TITLE
Kingfisher causing crash when support activity gets opened

### ISSUE THREAD

**Issue by hamzabinamin** [customerly/Customerly-iOS-SDK#3]
Your SDK is using Kingfisher as pods and it's causing an exception when ever I try to open the support view controller. 

The exception is as following:

`Thread 8: EXC_BREAKPOINT (code=EXC_ARM_BREAKPOINT, subcode=0xdefe)`

```
    var timeInterval: TimeInterval {
        switch self {
        case .never: return .infinity
        case .seconds(let seconds): return seconds
        case .days(let days): return TimeInterval(TimeConstants.secondsInOneDay * days)
        case .date(let ref): return ref.timeIntervalSinceNow
        case .expired: return -(.infinity)
        }
    }
```

The exception occurs at the `case.days `line

**Comment by hamzabinamin** [comment]
@pmusolino @lucamicheli @giannign1 @harrycamelback  can you look into this please

**Comment by harrycamelback** [comment]
Hi there.
Can you tell me on what version of Xcode do you have this problem?
Are you using the latest version of the SDK?
The crash happens only on a particular version of iOS?

**Comment by hamzabinamin** [comment]
@harrycamelback Hi Harry,

I'm on Xcode 11, I've tested on iOS 10 and 13, and it happens on both. And yes I'm on the latest version of the SDK.

**Comment by harrycamelback** [comment]
This is really strange, I don't get any crash on Xcode 11.
How do you configured the SDK? How to do you present it?

**Comment by hamzabinamin** [comment]
I think I figured out why the crash happens. I'm using kingfisher as a pod file in my app as well. So there are two binaries now which are causing the crash. 

Why exactly is kingfisher being used in customerly? Can we disable it or force it to use the pod present in my app?

**Comment by harrycamelback** [comment]
Since you are using Kingfisher in your app, you only need to delete the pod on your side, since the SDK import it for all the targets.

**Comment by hamzabinamin** [comment]
@harrycamelback What version is Customerly using for kingfisher?

**Comment by harrycamelback** [comment]
As you can see from our [podspec](https://github.com/customerly/Customerly-iOS-SDK/blob/master/CustomerlySDK.podspec), we are using v.5.7.0. We will update it into the next release.

**Comment by hamzabinamin** [comment]
@harrycamelback Upon further testing I have found out that this issue still occurs on iOS 10 but is not happening on iOS 13. 

Here's a screenshot of what the exception looks like:

![C1](https://user-images.githubusercontent.com/12872039/70545973-3feda180-1b90-11ea-80be-13c0c25d643d.PNG)

**Comment by hamzabinamin** [comment]
@lucamicheli I see that you're the founder of Customerly. We went with your SDK because we believed it would provide a stable solution in our apps however I have found that there are a lot of small bugs in your SDKs. I coordinated with the android developer last month and he was helpful however in our beta testing we have found a couple of other bugs as well. I have opened an issue on the android sdk for more than 2 weeks now, no one replies there.

And there's also an issue on the iOS side as you can see in the issue I posted above.

We're planning on shifting to the paid plan but I am sorry to say, the customer support hasn't been great. If this is how things are going to be then unfortunately we would need to shift to other solutions.

Can you please look into this and ask the devs to please at least reply.

Thank You
