### ISSUE TITLE
Dark Mode doesn't render text properly

### ISSUE THREAD

**Issue by davidhakki** [customerly/Customerly-iOS-SDK#4]
![IMG_181DD306E3A3-1](https://user-images.githubusercontent.com/12222977/67738446-0cdabe80-f9e5-11e9-97a6-11b020213f8d.jpeg)

Picture speaks a thousand words. The text appears to be white/invisible but when you hit enter you can see it on the blue background.

**Comment by harrycamelback** [comment]
Hi there. We will improve dark mode on iOS!
We plan to release a quick fix to correct the problem.

**Comment by harrycamelback** [comment]
Hi there.
We released a fix for that. You can use from now the new version 3.1.0.
