### ISSUE TITLE
Project Catalyst compatibility

### ISSUE THREAD

**Issue by davidhakki** [customerly/Customerly-iOS-SDK#5]
Any word or instructions on project catalyst compatibility. We have converted an iOS app to macOS but unfortunately it appears customerly will not build.

**Comment by harrycamelback** [comment]
Hi there. 
I'm so sorry but at the moment we don't have in plan to support catalyst. Maybe in the future, At the moment the adoption does not justify the efforts.
I suggest you to remove Customerly from dependencies when compile for catalyst.
